# Generated by Django 4.2.1 on 2023-05-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('price', models.FloatField(verbose_name='Ціна продажу')),
                ('profit', models.IntegerField(verbose_name='Прибуток')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.item', verbose_name='Назва товару')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateField(auto_now_add=True)),
                ('items_data', models.ManyToManyField(related_name='connection_items', to='common.outcomingitem')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('price', models.FloatField(verbose_name='Ціна закупівлі')),
                ('warehouse', models.IntegerField(verbose_name='Залишок на складі')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.item', verbose_name='Назва товару')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateField(auto_now_add=True)),
                ('items_data', models.ManyToManyField(related_name='connection_items', to='common.incomingitem')),
            ],
        ),
    ]
